# Generated by Django 4.1.1 on 2022-09-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='units',
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='filter',
            field=models.CharField(blank=True, choices=[('range', 'range'), ('single', 'single'), ('multi', 'multi')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='units',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
