# Generated by Django 4.1.1 on 2022-09-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_attribute_units_categoryattribute_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryattribute',
            old_name='filter',
            new_name='filter_type',
        ),
    ]
